apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "libero-reviewer.fullname" . }}-client
  labels:
    app.kubernetes.io/name: {{ include "libero-reviewer.name" . }}
    helm.sh/chart: {{ include "libero-reviewer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.public.json: |
    {
        "client_login_url": "https://{{ include "libero-reviewer.fullname" . }}.elifesciences.org/submit",
        "client_api_url": "https://{{ include "libero-reviewer.fullname" . }}-submission
    }
  config.infra.json: |
    {
        "port": 9000,
        "client_api_proxy_url": "http://{{ include "libero-reviewer.fullname" . }}-continuum-adaptor",
        "client_token_exchange_proxy_url":  "http://{{ include "libero-reviewer.fullname" . }}-continuum-adaptor/authenticate/",
        "new_relic_client_license_key": "",
        "new_relic_client_app_id": ""
    }